### ISSUE TITLE
Hide the API key and make this long string a constant

### ISSUE THREAD

**Issue by alexweininger** [dborg291/WorldOfTanksClanManager#1]
If any of that is sensitive then you want to hide it. Somebody could use it to make API calls on behalf of your application.

https://github.com/dborg291/WorldOfTanksClanManager/blob/8028b39498a2c12b1b682e0e2e1997be8db3db55/src/views/Strongholds.js#L21

**Comment by dborg291** [comment]
With the Wargaming API, there is not an API Key. There is an application id that is only used for usage tracking and is publicly searchable therefore hiding it is not necessary.
